development:
  adapter: postgresql
  encoding: unicode
  database: buckets_development
  pool: 5
  username: postgres
  password: pancake

test: &test
  adapter: postgresql
  encoding: unicode
  database: buckets_test
  pool: 5
  username: postgres
  password: pancake

cucumber:
  <<: *test