development:
  adapter: postgresql
  encoding: unicode
  database: buckets_development
  pool: 5
  username: jasonmccarthy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: buckets_test
  pool: 5
  username: jasonmccarthy
  password:
