development:
  adapter: postgresql
  encoding: unicode
  database: buckets_development
  pool: 5
  username: jasonmccarthy
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: buckets_test
  pool: 5
  username: jasonmccarthy
  password:

cucumber:
  <<: *test